import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { stripe, corsHeaders } from '../_shared/stripe.ts'

console.log('Stripe Connect (Custom) Function Started')

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const authHeader = req.headers.get('Authorization')
    if (!authHeader) throw new Error('Missing Authorization header')
    const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader
    const { data: { user }, error: userError } = await supabaseAdmin.auth.getUser(token)
    if (userError || !user) throw new Error('Unauthorized')

    const { 
      firstName, 
      lastName, 
      dobDay, 
      dobMonth, 
      dobYear, 
      taxId, // CPF
      bankCode, 
      branchCode, 
      accountNumber,
      phone,
      address,
      city,
      state,
      postalCode
    } = await req.json()

    // 1. Check if user already has a Stripe Account ID
    const { data: worker } = await supabaseAdmin
      .from('workers')
      .select('stripe_account_id')
      .eq('id', user.id)
      .single()

    let accountId = worker?.stripe_account_id

    // 2. Create or Update Stripe Account
    if (!accountId) {
      // Create new Custom Account
      const account = await stripe.accounts.create({
        type: 'custom',
        country: 'BR',
        email: user.email,
        business_type: 'individual',
        capabilities: {
          card_payments: { requested: true },
          transfers: { requested: true },
        },
        business_profile: {
            mcc: '5734', // Computer Software Stores (Generic for digital services)
            url: 'https://worki.com', // Placeholder
            product_description: 'Serviços freelance na plataforma Worki'
        },
        individual: {
            email: user.email,
            first_name: firstName,
            last_name: lastName,
            dob: {
                day: dobDay,
                month: dobMonth,
                year: dobYear
            },
            id_number: taxId, // CPF
            phone: phone,
            address: {
                line1: address,
                city: city,
                state: state,
                postal_code: postalCode,
                country: 'BR'
            }
        },
        settings: {
            payouts: {
                schedule: {
                    interval: 'manual' // CRITICAL: Disable automatic payouts
                }
            }
        },
        tos_acceptance: {
            date: Math.floor(Date.now() / 1000),
            ip: req.headers.get('x-forwarded-for') || '127.0.0.1', // Client IP
        }
      })
      accountId = account.id

      // Save ID to DB
      await supabaseAdmin
        .from('workers')
        .update({ stripe_account_id: accountId })
        .eq('id', user.id)
    } else {
        // Update existing account
        await stripe.accounts.update(accountId, {
            individual: {
                first_name: firstName,
                last_name: lastName,
                dob: {
                    day: dobDay,
                    month: dobMonth,
                    year: dobYear
                },
                id_number: taxId,
                phone: phone,
                address: {
                    line1: address,
                    city: city,
                    state: state,
                    postal_code: postalCode,
                    country: 'BR'
                }
            },
            tos_acceptance: {
                date: Math.floor(Date.now() / 1000),
                ip: req.headers.get('x-forwarded-for') || '127.0.0.1',
            }
        })
    }

    // 3. Attach Bank Account (External Account)
    // Note: In production, you should tokenize this data in frontend using Stripe Elements for PCI compliance.
    // For Custom accounts, passing via API is allowed but requires high security handling.
    // Ideally, use a token generated by stripe.createToken('bank_account', ...) in frontend.
    // Assuming we receive a 'bankAccountToken' would be safer, but for this exercise we map fields directly 
    // to show the "White Label" concept clearly.
    
    // For Brazilian accounts, Stripe expects:
    // bank_code, branch_code, account_number, account_holder_name, account_holder_type, currency='BRL', country='BR'
    
    const bankAccountData = {
        object: 'bank_account',
        country: 'BR',
        currency: 'BRL',
        account_holder_name: `${firstName} ${lastName}`,
        account_holder_type: 'individual',
        routing_number: `${bankCode}-${branchCode}`, // Bank-Branch format varies, Stripe BR often uses bank_code as routing number or specific format
        account_number: accountNumber
        // Note: Stripe Brazil integration details for External Accounts can be tricky.
        // Usually: routing_number = Bank Code (3 digits) + Branch Code (4 digits).
        // Let's assume standard Stripe API for BR.
    }
    
    // Better approach: Create External Account
    // Stripe BR requires 'bank_code', 'branch_code', 'account_number'
    // But the standard API uses 'routing_number' and 'account_number'.
    // For BR: routing_number should be the Bank Code (e.g., "001" for Banco do Brasil) usually, 
    // and branch goes into specific field or combined.
    // Let's use the external_account creation with raw details if token not provided.
    
    // Deleting old bank accounts to keep only the newest one (simple logic)
    const externalAccounts = await stripe.accounts.listExternalAccounts(accountId, { object: 'bank_account' })
    for (const acc of externalAccounts.data) {
        await stripe.accounts.deleteExternalAccount(accountId, acc.id)
    }

    await stripe.accounts.createExternalAccount(accountId, {
        external_account: {
            object: 'bank_account',
            country: 'BR',
            currency: 'BRL',
            account_holder_name: `${firstName} ${lastName}`,
            account_holder_type: 'individual',
            routing_number: bankCode, // 3 digits bank code
            account_number: `${branchCode}${accountNumber}` // Usually branch + account. Stripe docs specific for BR needed here.
            // Simplified for prototype. In real world, use Stripe.js in frontend to create a token.
        }
    })
    
    // Mark as completed in DB
    await supabaseAdmin
        .from('workers')
        .update({ stripe_onboarding_completed: true })
        .eq('id', user.id)

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    console.error('Error:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
